/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "led.h"
#include "uart.h"
//#include "timebase.h"
#include "osKernel.h"

#define QUANTA 		2

typedef uint32_t TaskProfiler;

TaskProfiler Task0_Profiler, Task1_Profiler, Task2_Profiler;

uint32_t semaphore1, semaphore2;

void motor_run();
void motor_stop();
void valve_open();
void valve_close();


void task0()
{
	while(1)
	{
		osSemaphoreWait(&semaphore1);
		Task0_Profiler++;
		motor_run();
		osSemaphorePost(&semaphore2);
	}
}

void task1()
{
	while(1)
	{
		osSemaphoreWait(&semaphore2);
		Task1_Profiler++;
		valve_open();
		osSemaphorePost(&semaphore1);
	}
}

void task2()
{
	while(1)
	{
		Task2_Profiler++;
	}
}


int main()
{

	// Initialize UART.
	uart_tx_init();

	// Initialize semaphores.
	osSemaphoreInit(&semaphore1, 1);
	osSemaphoreInit(&semaphore2, 0);

	// Initialize kernel.
	osKernelInit();

	// Add threads.
	osKernelAddThreads(&task0, &task1, &task2);

	// Launch the kernel.
	osKernelLaunch(QUANTA);
}

void motor_run()
{
	printf("motor is running...\n\r");
}

void motor_stop()
{
	printf("motor is stopping...\n\r");
}

void valve_open()
{
	printf("valve is opening...\n\r");
}

void valve_close()
{
	printf("valve is closing...\n\r");
}












